# como es temporal para compilar usamos la version full en vez de la -alpine
FROM node:lts AS builder
WORKDIR /usr/src/
COPY ./ .
RUN npm i
RUN npm run build

FROM nginx
# modified default output Path to dist in angular.json projects.test-app.architect.build.outputPath
COPY --from=builder /usr/src/dist/ /usr/share/nginx/html

CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/settings.template.json > /usr/share/nginx/html/assets/settings.json && exec nginx -g 'daemon off;'"]
